//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Einvoice_Customer.HDDT.PortalService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PortalServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PortalService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback listInvByCusOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchInvOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCatalogViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInvViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInvViewNoPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback convertForStoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback convertForVerifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadInvOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadInvNoPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadInvPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadInvPDFNoPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback listInvByCusFkeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback listInvByCusFkeyVNPOperationCompleted;
        
        private System.Threading.SendOrPostCallback getcatalogViewFkeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadInvPDFFkeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadInvPDFFkeyNoPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInvViewFkeyByStaffOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInvViewFkeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInvViewFkeyNoPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback convertForStoreFkeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback convertForVerifyFkeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadInvFkeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadInvFkeyNoPayOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDigestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmSigantureOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStaffOperationCompleted;
        
        private System.Threading.SendOrPostCallback listInvFromNoToNoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PortalService() {
            this.Url = global::Einvoice_Customer.Properties.Settings.Default.Einvoice_Customer_HDDT_PortalService_PortalService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event listInvByCusCompletedEventHandler listInvByCusCompleted;
        
        /// <remarks/>
        public event SearchInvCompletedEventHandler SearchInvCompleted;
        
        /// <remarks/>
        public event getCatalogViewCompletedEventHandler getCatalogViewCompleted;
        
        /// <remarks/>
        public event getInvViewCompletedEventHandler getInvViewCompleted;
        
        /// <remarks/>
        public event getInvViewNoPayCompletedEventHandler getInvViewNoPayCompleted;
        
        /// <remarks/>
        public event convertForStoreCompletedEventHandler convertForStoreCompleted;
        
        /// <remarks/>
        public event convertForVerifyCompletedEventHandler convertForVerifyCompleted;
        
        /// <remarks/>
        public event downloadInvCompletedEventHandler downloadInvCompleted;
        
        /// <remarks/>
        public event downloadInvNoPayCompletedEventHandler downloadInvNoPayCompleted;
        
        /// <remarks/>
        public event downloadInvPDFCompletedEventHandler downloadInvPDFCompleted;
        
        /// <remarks/>
        public event downloadInvPDFNoPayCompletedEventHandler downloadInvPDFNoPayCompleted;
        
        /// <remarks/>
        public event listInvByCusFkeyCompletedEventHandler listInvByCusFkeyCompleted;
        
        /// <remarks/>
        public event listInvByCusFkeyVNPCompletedEventHandler listInvByCusFkeyVNPCompleted;
        
        /// <remarks/>
        public event getcatalogViewFkeyCompletedEventHandler getcatalogViewFkeyCompleted;
        
        /// <remarks/>
        public event downloadInvPDFFkeyCompletedEventHandler downloadInvPDFFkeyCompleted;
        
        /// <remarks/>
        public event downloadInvPDFFkeyNoPayCompletedEventHandler downloadInvPDFFkeyNoPayCompleted;
        
        /// <remarks/>
        public event getInvViewFkeyByStaffCompletedEventHandler getInvViewFkeyByStaffCompleted;
        
        /// <remarks/>
        public event getInvViewFkeyCompletedEventHandler getInvViewFkeyCompleted;
        
        /// <remarks/>
        public event getInvViewFkeyNoPayCompletedEventHandler getInvViewFkeyNoPayCompleted;
        
        /// <remarks/>
        public event convertForStoreFkeyCompletedEventHandler convertForStoreFkeyCompleted;
        
        /// <remarks/>
        public event convertForVerifyFkeyCompletedEventHandler convertForVerifyFkeyCompleted;
        
        /// <remarks/>
        public event downloadInvFkeyCompletedEventHandler downloadInvFkeyCompleted;
        
        /// <remarks/>
        public event downloadInvFkeyNoPayCompletedEventHandler downloadInvFkeyNoPayCompleted;
        
        /// <remarks/>
        public event getDigestCompletedEventHandler getDigestCompleted;
        
        /// <remarks/>
        public event ConfirmSigantureCompletedEventHandler ConfirmSigantureCompleted;
        
        /// <remarks/>
        public event getCusCompletedEventHandler getCusCompleted;
        
        /// <remarks/>
        public event getStaffCompletedEventHandler getStaffCompleted;
        
        /// <remarks/>
        public event listInvFromNoToNoCompletedEventHandler listInvFromNoToNoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listInvByCus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string listInvByCus(string cusCode, string fromDate, string toDate, string userName, string userPass) {
            object[] results = this.Invoke("listInvByCus", new object[] {
                        cusCode,
                        fromDate,
                        toDate,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void listInvByCusAsync(string cusCode, string fromDate, string toDate, string userName, string userPass) {
            this.listInvByCusAsync(cusCode, fromDate, toDate, userName, userPass, null);
        }
        
        /// <remarks/>
        public void listInvByCusAsync(string cusCode, string fromDate, string toDate, string userName, string userPass, object userState) {
            if ((this.listInvByCusOperationCompleted == null)) {
                this.listInvByCusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistInvByCusOperationCompleted);
            }
            this.InvokeAsync("listInvByCus", new object[] {
                        cusCode,
                        fromDate,
                        toDate,
                        userName,
                        userPass}, this.listInvByCusOperationCompleted, userState);
        }
        
        private void OnlistInvByCusOperationCompleted(object arg) {
            if ((this.listInvByCusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listInvByCusCompleted(this, new listInvByCusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchInv", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SearchInv(string cusCode, string pattern, string serial, string fromDate, string toDate, string invNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> invStatus, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> page, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> cussignStatus, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> payment, string userName, string userPass) {
            object[] results = this.Invoke("SearchInv", new object[] {
                        cusCode,
                        pattern,
                        serial,
                        fromDate,
                        toDate,
                        invNumber,
                        invStatus,
                        page,
                        cussignStatus,
                        payment,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchInvAsync(string cusCode, string pattern, string serial, string fromDate, string toDate, string invNumber, System.Nullable<int> invStatus, System.Nullable<int> page, System.Nullable<int> cussignStatus, System.Nullable<int> payment, string userName, string userPass) {
            this.SearchInvAsync(cusCode, pattern, serial, fromDate, toDate, invNumber, invStatus, page, cussignStatus, payment, userName, userPass, null);
        }
        
        /// <remarks/>
        public void SearchInvAsync(string cusCode, string pattern, string serial, string fromDate, string toDate, string invNumber, System.Nullable<int> invStatus, System.Nullable<int> page, System.Nullable<int> cussignStatus, System.Nullable<int> payment, string userName, string userPass, object userState) {
            if ((this.SearchInvOperationCompleted == null)) {
                this.SearchInvOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchInvOperationCompleted);
            }
            this.InvokeAsync("SearchInv", new object[] {
                        cusCode,
                        pattern,
                        serial,
                        fromDate,
                        toDate,
                        invNumber,
                        invStatus,
                        page,
                        cussignStatus,
                        payment,
                        userName,
                        userPass}, this.SearchInvOperationCompleted, userState);
        }
        
        private void OnSearchInvOperationCompleted(object arg) {
            if ((this.SearchInvCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchInvCompleted(this, new SearchInvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCatalogView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCatalogView(string invToken, string userName, string userPass) {
            object[] results = this.Invoke("getCatalogView", new object[] {
                        invToken,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCatalogViewAsync(string invToken, string userName, string userPass) {
            this.getCatalogViewAsync(invToken, userName, userPass, null);
        }
        
        /// <remarks/>
        public void getCatalogViewAsync(string invToken, string userName, string userPass, object userState) {
            if ((this.getCatalogViewOperationCompleted == null)) {
                this.getCatalogViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCatalogViewOperationCompleted);
            }
            this.InvokeAsync("getCatalogView", new object[] {
                        invToken,
                        userName,
                        userPass}, this.getCatalogViewOperationCompleted, userState);
        }
        
        private void OngetCatalogViewOperationCompleted(object arg) {
            if ((this.getCatalogViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCatalogViewCompleted(this, new getCatalogViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInvView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInvView(string invToken, string userName, string userPass) {
            object[] results = this.Invoke("getInvView", new object[] {
                        invToken,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getInvViewAsync(string invToken, string userName, string userPass) {
            this.getInvViewAsync(invToken, userName, userPass, null);
        }
        
        /// <remarks/>
        public void getInvViewAsync(string invToken, string userName, string userPass, object userState) {
            if ((this.getInvViewOperationCompleted == null)) {
                this.getInvViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInvViewOperationCompleted);
            }
            this.InvokeAsync("getInvView", new object[] {
                        invToken,
                        userName,
                        userPass}, this.getInvViewOperationCompleted, userState);
        }
        
        private void OngetInvViewOperationCompleted(object arg) {
            if ((this.getInvViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInvViewCompleted(this, new getInvViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInvViewNoPay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInvViewNoPay(string invToken, string userName, string userPass) {
            object[] results = this.Invoke("getInvViewNoPay", new object[] {
                        invToken,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getInvViewNoPayAsync(string invToken, string userName, string userPass) {
            this.getInvViewNoPayAsync(invToken, userName, userPass, null);
        }
        
        /// <remarks/>
        public void getInvViewNoPayAsync(string invToken, string userName, string userPass, object userState) {
            if ((this.getInvViewNoPayOperationCompleted == null)) {
                this.getInvViewNoPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInvViewNoPayOperationCompleted);
            }
            this.InvokeAsync("getInvViewNoPay", new object[] {
                        invToken,
                        userName,
                        userPass}, this.getInvViewNoPayOperationCompleted, userState);
        }
        
        private void OngetInvViewNoPayOperationCompleted(object arg) {
            if ((this.getInvViewNoPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInvViewNoPayCompleted(this, new getInvViewNoPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/convertForStore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string convertForStore(string invToken, string userName, string userPass) {
            object[] results = this.Invoke("convertForStore", new object[] {
                        invToken,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void convertForStoreAsync(string invToken, string userName, string userPass) {
            this.convertForStoreAsync(invToken, userName, userPass, null);
        }
        
        /// <remarks/>
        public void convertForStoreAsync(string invToken, string userName, string userPass, object userState) {
            if ((this.convertForStoreOperationCompleted == null)) {
                this.convertForStoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconvertForStoreOperationCompleted);
            }
            this.InvokeAsync("convertForStore", new object[] {
                        invToken,
                        userName,
                        userPass}, this.convertForStoreOperationCompleted, userState);
        }
        
        private void OnconvertForStoreOperationCompleted(object arg) {
            if ((this.convertForStoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.convertForStoreCompleted(this, new convertForStoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/convertForVerify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string convertForVerify(string invToken, string userName, string userPass) {
            object[] results = this.Invoke("convertForVerify", new object[] {
                        invToken,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void convertForVerifyAsync(string invToken, string userName, string userPass) {
            this.convertForVerifyAsync(invToken, userName, userPass, null);
        }
        
        /// <remarks/>
        public void convertForVerifyAsync(string invToken, string userName, string userPass, object userState) {
            if ((this.convertForVerifyOperationCompleted == null)) {
                this.convertForVerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconvertForVerifyOperationCompleted);
            }
            this.InvokeAsync("convertForVerify", new object[] {
                        invToken,
                        userName,
                        userPass}, this.convertForVerifyOperationCompleted, userState);
        }
        
        private void OnconvertForVerifyOperationCompleted(object arg) {
            if ((this.convertForVerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.convertForVerifyCompleted(this, new convertForVerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/downloadInv", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string downloadInv(string invToken, string userName, string userPass) {
            object[] results = this.Invoke("downloadInv", new object[] {
                        invToken,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downloadInvAsync(string invToken, string userName, string userPass) {
            this.downloadInvAsync(invToken, userName, userPass, null);
        }
        
        /// <remarks/>
        public void downloadInvAsync(string invToken, string userName, string userPass, object userState) {
            if ((this.downloadInvOperationCompleted == null)) {
                this.downloadInvOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadInvOperationCompleted);
            }
            this.InvokeAsync("downloadInv", new object[] {
                        invToken,
                        userName,
                        userPass}, this.downloadInvOperationCompleted, userState);
        }
        
        private void OndownloadInvOperationCompleted(object arg) {
            if ((this.downloadInvCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadInvCompleted(this, new downloadInvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/downloadInvNoPay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string downloadInvNoPay(string invToken, string userName, string userPass) {
            object[] results = this.Invoke("downloadInvNoPay", new object[] {
                        invToken,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downloadInvNoPayAsync(string invToken, string userName, string userPass) {
            this.downloadInvNoPayAsync(invToken, userName, userPass, null);
        }
        
        /// <remarks/>
        public void downloadInvNoPayAsync(string invToken, string userName, string userPass, object userState) {
            if ((this.downloadInvNoPayOperationCompleted == null)) {
                this.downloadInvNoPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadInvNoPayOperationCompleted);
            }
            this.InvokeAsync("downloadInvNoPay", new object[] {
                        invToken,
                        userName,
                        userPass}, this.downloadInvNoPayOperationCompleted, userState);
        }
        
        private void OndownloadInvNoPayOperationCompleted(object arg) {
            if ((this.downloadInvNoPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadInvNoPayCompleted(this, new downloadInvNoPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/downloadInvPDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string downloadInvPDF(string token, string userName, string userPass) {
            object[] results = this.Invoke("downloadInvPDF", new object[] {
                        token,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downloadInvPDFAsync(string token, string userName, string userPass) {
            this.downloadInvPDFAsync(token, userName, userPass, null);
        }
        
        /// <remarks/>
        public void downloadInvPDFAsync(string token, string userName, string userPass, object userState) {
            if ((this.downloadInvPDFOperationCompleted == null)) {
                this.downloadInvPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadInvPDFOperationCompleted);
            }
            this.InvokeAsync("downloadInvPDF", new object[] {
                        token,
                        userName,
                        userPass}, this.downloadInvPDFOperationCompleted, userState);
        }
        
        private void OndownloadInvPDFOperationCompleted(object arg) {
            if ((this.downloadInvPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadInvPDFCompleted(this, new downloadInvPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/downloadInvPDFNoPay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string downloadInvPDFNoPay(string token, string userName, string userPass) {
            object[] results = this.Invoke("downloadInvPDFNoPay", new object[] {
                        token,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downloadInvPDFNoPayAsync(string token, string userName, string userPass) {
            this.downloadInvPDFNoPayAsync(token, userName, userPass, null);
        }
        
        /// <remarks/>
        public void downloadInvPDFNoPayAsync(string token, string userName, string userPass, object userState) {
            if ((this.downloadInvPDFNoPayOperationCompleted == null)) {
                this.downloadInvPDFNoPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadInvPDFNoPayOperationCompleted);
            }
            this.InvokeAsync("downloadInvPDFNoPay", new object[] {
                        token,
                        userName,
                        userPass}, this.downloadInvPDFNoPayOperationCompleted, userState);
        }
        
        private void OndownloadInvPDFNoPayOperationCompleted(object arg) {
            if ((this.downloadInvPDFNoPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadInvPDFNoPayCompleted(this, new downloadInvPDFNoPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listInvByCusFkey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string listInvByCusFkey(string key, string fromDate, string toDate, string userName, string userPass) {
            object[] results = this.Invoke("listInvByCusFkey", new object[] {
                        key,
                        fromDate,
                        toDate,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void listInvByCusFkeyAsync(string key, string fromDate, string toDate, string userName, string userPass) {
            this.listInvByCusFkeyAsync(key, fromDate, toDate, userName, userPass, null);
        }
        
        /// <remarks/>
        public void listInvByCusFkeyAsync(string key, string fromDate, string toDate, string userName, string userPass, object userState) {
            if ((this.listInvByCusFkeyOperationCompleted == null)) {
                this.listInvByCusFkeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistInvByCusFkeyOperationCompleted);
            }
            this.InvokeAsync("listInvByCusFkey", new object[] {
                        key,
                        fromDate,
                        toDate,
                        userName,
                        userPass}, this.listInvByCusFkeyOperationCompleted, userState);
        }
        
        private void OnlistInvByCusFkeyOperationCompleted(object arg) {
            if ((this.listInvByCusFkeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listInvByCusFkeyCompleted(this, new listInvByCusFkeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listInvByCusFkeyVNP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string listInvByCusFkeyVNP(string key, string fromDate, string toDate, string userName, string userPass) {
            object[] results = this.Invoke("listInvByCusFkeyVNP", new object[] {
                        key,
                        fromDate,
                        toDate,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void listInvByCusFkeyVNPAsync(string key, string fromDate, string toDate, string userName, string userPass) {
            this.listInvByCusFkeyVNPAsync(key, fromDate, toDate, userName, userPass, null);
        }
        
        /// <remarks/>
        public void listInvByCusFkeyVNPAsync(string key, string fromDate, string toDate, string userName, string userPass, object userState) {
            if ((this.listInvByCusFkeyVNPOperationCompleted == null)) {
                this.listInvByCusFkeyVNPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistInvByCusFkeyVNPOperationCompleted);
            }
            this.InvokeAsync("listInvByCusFkeyVNP", new object[] {
                        key,
                        fromDate,
                        toDate,
                        userName,
                        userPass}, this.listInvByCusFkeyVNPOperationCompleted, userState);
        }
        
        private void OnlistInvByCusFkeyVNPOperationCompleted(object arg) {
            if ((this.listInvByCusFkeyVNPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listInvByCusFkeyVNPCompleted(this, new listInvByCusFkeyVNPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getcatalogViewFkey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getcatalogViewFkey(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("getcatalogViewFkey", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getcatalogViewFkeyAsync(string fkey, string userName, string userPass) {
            this.getcatalogViewFkeyAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void getcatalogViewFkeyAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.getcatalogViewFkeyOperationCompleted == null)) {
                this.getcatalogViewFkeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetcatalogViewFkeyOperationCompleted);
            }
            this.InvokeAsync("getcatalogViewFkey", new object[] {
                        fkey,
                        userName,
                        userPass}, this.getcatalogViewFkeyOperationCompleted, userState);
        }
        
        private void OngetcatalogViewFkeyOperationCompleted(object arg) {
            if ((this.getcatalogViewFkeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getcatalogViewFkeyCompleted(this, new getcatalogViewFkeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/downloadInvPDFFkey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string downloadInvPDFFkey(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("downloadInvPDFFkey", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downloadInvPDFFkeyAsync(string fkey, string userName, string userPass) {
            this.downloadInvPDFFkeyAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void downloadInvPDFFkeyAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.downloadInvPDFFkeyOperationCompleted == null)) {
                this.downloadInvPDFFkeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadInvPDFFkeyOperationCompleted);
            }
            this.InvokeAsync("downloadInvPDFFkey", new object[] {
                        fkey,
                        userName,
                        userPass}, this.downloadInvPDFFkeyOperationCompleted, userState);
        }
        
        private void OndownloadInvPDFFkeyOperationCompleted(object arg) {
            if ((this.downloadInvPDFFkeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadInvPDFFkeyCompleted(this, new downloadInvPDFFkeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/downloadInvPDFFkeyNoPay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string downloadInvPDFFkeyNoPay(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("downloadInvPDFFkeyNoPay", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downloadInvPDFFkeyNoPayAsync(string fkey, string userName, string userPass) {
            this.downloadInvPDFFkeyNoPayAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void downloadInvPDFFkeyNoPayAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.downloadInvPDFFkeyNoPayOperationCompleted == null)) {
                this.downloadInvPDFFkeyNoPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadInvPDFFkeyNoPayOperationCompleted);
            }
            this.InvokeAsync("downloadInvPDFFkeyNoPay", new object[] {
                        fkey,
                        userName,
                        userPass}, this.downloadInvPDFFkeyNoPayOperationCompleted, userState);
        }
        
        private void OndownloadInvPDFFkeyNoPayOperationCompleted(object arg) {
            if ((this.downloadInvPDFFkeyNoPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadInvPDFFkeyNoPayCompleted(this, new downloadInvPDFFkeyNoPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInvViewFkeyByStaff", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInvViewFkeyByStaff(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("getInvViewFkeyByStaff", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getInvViewFkeyByStaffAsync(string fkey, string userName, string userPass) {
            this.getInvViewFkeyByStaffAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void getInvViewFkeyByStaffAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.getInvViewFkeyByStaffOperationCompleted == null)) {
                this.getInvViewFkeyByStaffOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInvViewFkeyByStaffOperationCompleted);
            }
            this.InvokeAsync("getInvViewFkeyByStaff", new object[] {
                        fkey,
                        userName,
                        userPass}, this.getInvViewFkeyByStaffOperationCompleted, userState);
        }
        
        private void OngetInvViewFkeyByStaffOperationCompleted(object arg) {
            if ((this.getInvViewFkeyByStaffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInvViewFkeyByStaffCompleted(this, new getInvViewFkeyByStaffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInvViewFkey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInvViewFkey(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("getInvViewFkey", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getInvViewFkeyAsync(string fkey, string userName, string userPass) {
            this.getInvViewFkeyAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void getInvViewFkeyAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.getInvViewFkeyOperationCompleted == null)) {
                this.getInvViewFkeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInvViewFkeyOperationCompleted);
            }
            this.InvokeAsync("getInvViewFkey", new object[] {
                        fkey,
                        userName,
                        userPass}, this.getInvViewFkeyOperationCompleted, userState);
        }
        
        private void OngetInvViewFkeyOperationCompleted(object arg) {
            if ((this.getInvViewFkeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInvViewFkeyCompleted(this, new getInvViewFkeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInvViewFkeyNoPay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInvViewFkeyNoPay(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("getInvViewFkeyNoPay", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getInvViewFkeyNoPayAsync(string fkey, string userName, string userPass) {
            this.getInvViewFkeyNoPayAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void getInvViewFkeyNoPayAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.getInvViewFkeyNoPayOperationCompleted == null)) {
                this.getInvViewFkeyNoPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInvViewFkeyNoPayOperationCompleted);
            }
            this.InvokeAsync("getInvViewFkeyNoPay", new object[] {
                        fkey,
                        userName,
                        userPass}, this.getInvViewFkeyNoPayOperationCompleted, userState);
        }
        
        private void OngetInvViewFkeyNoPayOperationCompleted(object arg) {
            if ((this.getInvViewFkeyNoPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInvViewFkeyNoPayCompleted(this, new getInvViewFkeyNoPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/convertForStoreFkey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string convertForStoreFkey(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("convertForStoreFkey", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void convertForStoreFkeyAsync(string fkey, string userName, string userPass) {
            this.convertForStoreFkeyAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void convertForStoreFkeyAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.convertForStoreFkeyOperationCompleted == null)) {
                this.convertForStoreFkeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconvertForStoreFkeyOperationCompleted);
            }
            this.InvokeAsync("convertForStoreFkey", new object[] {
                        fkey,
                        userName,
                        userPass}, this.convertForStoreFkeyOperationCompleted, userState);
        }
        
        private void OnconvertForStoreFkeyOperationCompleted(object arg) {
            if ((this.convertForStoreFkeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.convertForStoreFkeyCompleted(this, new convertForStoreFkeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/convertForVerifyFkey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string convertForVerifyFkey(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("convertForVerifyFkey", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void convertForVerifyFkeyAsync(string fkey, string userName, string userPass) {
            this.convertForVerifyFkeyAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void convertForVerifyFkeyAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.convertForVerifyFkeyOperationCompleted == null)) {
                this.convertForVerifyFkeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconvertForVerifyFkeyOperationCompleted);
            }
            this.InvokeAsync("convertForVerifyFkey", new object[] {
                        fkey,
                        userName,
                        userPass}, this.convertForVerifyFkeyOperationCompleted, userState);
        }
        
        private void OnconvertForVerifyFkeyOperationCompleted(object arg) {
            if ((this.convertForVerifyFkeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.convertForVerifyFkeyCompleted(this, new convertForVerifyFkeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/downloadInvFkey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string downloadInvFkey(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("downloadInvFkey", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downloadInvFkeyAsync(string fkey, string userName, string userPass) {
            this.downloadInvFkeyAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void downloadInvFkeyAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.downloadInvFkeyOperationCompleted == null)) {
                this.downloadInvFkeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadInvFkeyOperationCompleted);
            }
            this.InvokeAsync("downloadInvFkey", new object[] {
                        fkey,
                        userName,
                        userPass}, this.downloadInvFkeyOperationCompleted, userState);
        }
        
        private void OndownloadInvFkeyOperationCompleted(object arg) {
            if ((this.downloadInvFkeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadInvFkeyCompleted(this, new downloadInvFkeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/downloadInvFkeyNoPay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string downloadInvFkeyNoPay(string fkey, string userName, string userPass) {
            object[] results = this.Invoke("downloadInvFkeyNoPay", new object[] {
                        fkey,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void downloadInvFkeyNoPayAsync(string fkey, string userName, string userPass) {
            this.downloadInvFkeyNoPayAsync(fkey, userName, userPass, null);
        }
        
        /// <remarks/>
        public void downloadInvFkeyNoPayAsync(string fkey, string userName, string userPass, object userState) {
            if ((this.downloadInvFkeyNoPayOperationCompleted == null)) {
                this.downloadInvFkeyNoPayOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadInvFkeyNoPayOperationCompleted);
            }
            this.InvokeAsync("downloadInvFkeyNoPay", new object[] {
                        fkey,
                        userName,
                        userPass}, this.downloadInvFkeyNoPayOperationCompleted, userState);
        }
        
        private void OndownloadInvFkeyNoPayOperationCompleted(object arg) {
            if ((this.downloadInvFkeyNoPayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadInvFkeyNoPayCompleted(this, new downloadInvFkeyNoPayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDigest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getDigest(string cusCode, string invToken, string userName, string userPass) {
            object[] results = this.Invoke("getDigest", new object[] {
                        cusCode,
                        invToken,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDigestAsync(string cusCode, string invToken, string userName, string userPass) {
            this.getDigestAsync(cusCode, invToken, userName, userPass, null);
        }
        
        /// <remarks/>
        public void getDigestAsync(string cusCode, string invToken, string userName, string userPass, object userState) {
            if ((this.getDigestOperationCompleted == null)) {
                this.getDigestOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDigestOperationCompleted);
            }
            this.InvokeAsync("getDigest", new object[] {
                        cusCode,
                        invToken,
                        userName,
                        userPass}, this.getDigestOperationCompleted, userState);
        }
        
        private void OngetDigestOperationCompleted(object arg) {
            if ((this.getDigestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDigestCompleted(this, new getDigestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmSiganture", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfirmSiganture(string signValue, string invToken, string userName, string userPass) {
            object[] results = this.Invoke("ConfirmSiganture", new object[] {
                        signValue,
                        invToken,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmSigantureAsync(string signValue, string invToken, string userName, string userPass) {
            this.ConfirmSigantureAsync(signValue, invToken, userName, userPass, null);
        }
        
        /// <remarks/>
        public void ConfirmSigantureAsync(string signValue, string invToken, string userName, string userPass, object userState) {
            if ((this.ConfirmSigantureOperationCompleted == null)) {
                this.ConfirmSigantureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmSigantureOperationCompleted);
            }
            this.InvokeAsync("ConfirmSiganture", new object[] {
                        signValue,
                        invToken,
                        userName,
                        userPass}, this.ConfirmSigantureOperationCompleted, userState);
        }
        
        private void OnConfirmSigantureOperationCompleted(object arg) {
            if ((this.ConfirmSigantureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmSigantureCompleted(this, new ConfirmSigantureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCus(string cusCode, string userName, string userPass) {
            object[] results = this.Invoke("getCus", new object[] {
                        cusCode,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCusAsync(string cusCode, string userName, string userPass) {
            this.getCusAsync(cusCode, userName, userPass, null);
        }
        
        /// <remarks/>
        public void getCusAsync(string cusCode, string userName, string userPass, object userState) {
            if ((this.getCusOperationCompleted == null)) {
                this.getCusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCusOperationCompleted);
            }
            this.InvokeAsync("getCus", new object[] {
                        cusCode,
                        userName,
                        userPass}, this.getCusOperationCompleted, userState);
        }
        
        private void OngetCusOperationCompleted(object arg) {
            if ((this.getCusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCusCompleted(this, new getCusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getStaff", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getStaff(string accountName, string userName, string userPass) {
            object[] results = this.Invoke("getStaff", new object[] {
                        accountName,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStaffAsync(string accountName, string userName, string userPass) {
            this.getStaffAsync(accountName, userName, userPass, null);
        }
        
        /// <remarks/>
        public void getStaffAsync(string accountName, string userName, string userPass, object userState) {
            if ((this.getStaffOperationCompleted == null)) {
                this.getStaffOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStaffOperationCompleted);
            }
            this.InvokeAsync("getStaff", new object[] {
                        accountName,
                        userName,
                        userPass}, this.getStaffOperationCompleted, userState);
        }
        
        private void OngetStaffOperationCompleted(object arg) {
            if ((this.getStaffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStaffCompleted(this, new getStaffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listInvFromNoToNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string listInvFromNoToNo(string invFromNo, string invToNo, string invPattern, string invSerial, string userName, string userPass) {
            object[] results = this.Invoke("listInvFromNoToNo", new object[] {
                        invFromNo,
                        invToNo,
                        invPattern,
                        invSerial,
                        userName,
                        userPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void listInvFromNoToNoAsync(string invFromNo, string invToNo, string invPattern, string invSerial, string userName, string userPass) {
            this.listInvFromNoToNoAsync(invFromNo, invToNo, invPattern, invSerial, userName, userPass, null);
        }
        
        /// <remarks/>
        public void listInvFromNoToNoAsync(string invFromNo, string invToNo, string invPattern, string invSerial, string userName, string userPass, object userState) {
            if ((this.listInvFromNoToNoOperationCompleted == null)) {
                this.listInvFromNoToNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistInvFromNoToNoOperationCompleted);
            }
            this.InvokeAsync("listInvFromNoToNo", new object[] {
                        invFromNo,
                        invToNo,
                        invPattern,
                        invSerial,
                        userName,
                        userPass}, this.listInvFromNoToNoOperationCompleted, userState);
        }
        
        private void OnlistInvFromNoToNoOperationCompleted(object arg) {
            if ((this.listInvFromNoToNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listInvFromNoToNoCompleted(this, new listInvFromNoToNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void listInvByCusCompletedEventHandler(object sender, listInvByCusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listInvByCusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listInvByCusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SearchInvCompletedEventHandler(object sender, SearchInvCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchInvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchInvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCatalogViewCompletedEventHandler(object sender, getCatalogViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCatalogViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCatalogViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getInvViewCompletedEventHandler(object sender, getInvViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInvViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInvViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getInvViewNoPayCompletedEventHandler(object sender, getInvViewNoPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInvViewNoPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInvViewNoPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void convertForStoreCompletedEventHandler(object sender, convertForStoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class convertForStoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal convertForStoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void convertForVerifyCompletedEventHandler(object sender, convertForVerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class convertForVerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal convertForVerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void downloadInvCompletedEventHandler(object sender, downloadInvCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadInvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadInvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void downloadInvNoPayCompletedEventHandler(object sender, downloadInvNoPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadInvNoPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadInvNoPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void downloadInvPDFCompletedEventHandler(object sender, downloadInvPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadInvPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadInvPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void downloadInvPDFNoPayCompletedEventHandler(object sender, downloadInvPDFNoPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadInvPDFNoPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadInvPDFNoPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void listInvByCusFkeyCompletedEventHandler(object sender, listInvByCusFkeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listInvByCusFkeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listInvByCusFkeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void listInvByCusFkeyVNPCompletedEventHandler(object sender, listInvByCusFkeyVNPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listInvByCusFkeyVNPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listInvByCusFkeyVNPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getcatalogViewFkeyCompletedEventHandler(object sender, getcatalogViewFkeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getcatalogViewFkeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getcatalogViewFkeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void downloadInvPDFFkeyCompletedEventHandler(object sender, downloadInvPDFFkeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadInvPDFFkeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadInvPDFFkeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void downloadInvPDFFkeyNoPayCompletedEventHandler(object sender, downloadInvPDFFkeyNoPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadInvPDFFkeyNoPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadInvPDFFkeyNoPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getInvViewFkeyByStaffCompletedEventHandler(object sender, getInvViewFkeyByStaffCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInvViewFkeyByStaffCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInvViewFkeyByStaffCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getInvViewFkeyCompletedEventHandler(object sender, getInvViewFkeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInvViewFkeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInvViewFkeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getInvViewFkeyNoPayCompletedEventHandler(object sender, getInvViewFkeyNoPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInvViewFkeyNoPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInvViewFkeyNoPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void convertForStoreFkeyCompletedEventHandler(object sender, convertForStoreFkeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class convertForStoreFkeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal convertForStoreFkeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void convertForVerifyFkeyCompletedEventHandler(object sender, convertForVerifyFkeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class convertForVerifyFkeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal convertForVerifyFkeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void downloadInvFkeyCompletedEventHandler(object sender, downloadInvFkeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadInvFkeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadInvFkeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void downloadInvFkeyNoPayCompletedEventHandler(object sender, downloadInvFkeyNoPayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadInvFkeyNoPayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadInvFkeyNoPayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getDigestCompletedEventHandler(object sender, getDigestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDigestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDigestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ConfirmSigantureCompletedEventHandler(object sender, ConfirmSigantureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmSigantureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmSigantureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getCusCompletedEventHandler(object sender, getCusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getStaffCompletedEventHandler(object sender, getStaffCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStaffCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStaffCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void listInvFromNoToNoCompletedEventHandler(object sender, listInvFromNoToNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listInvFromNoToNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listInvFromNoToNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591