//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Einvoice_Customer.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Einvoice_Customer.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect..
        /// </summary>
        public static string accountnotExist {
            get {
                return ResourceManager.GetString("accountnotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Addr {
            get {
                return ResourceManager.GetString("Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:  105 Vo Nguyen Giap St, Khue My Ward, Ngu Hanh Son Dist, Da Nang City, Vietnam.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu Du Village, Loc Vinh Commune, Phu
        ///Loc District, Thua Thien Hue Province,
        ///Vietnam.
        /// </summary>
        public static string addval {
            get {
                return ResourceManager.GetString("addval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Credentials. Please check again..
        /// </summary>
        public static string alertCheckagain {
            get {
                return ResourceManager.GetString("alertCheckagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification of new password.
        /// </summary>
        public static string alertNewPass {
            get {
                return ResourceManager.GetString("alertNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pleasead to inform you that your password  just have been changed. Your new password is: .
        /// </summary>
        public static string alertNewPass1 {
            get {
                return ResourceManager.GetString("alertNewPass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please access.
        /// </summary>
        public static string alertNewPass2 {
            get {
                return ResourceManager.GetString("alertNewPass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to change the password..
        /// </summary>
        public static string alertNewPass3 {
            get {
                return ResourceManager.GetString("alertNewPass3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Name.
        /// </summary>
        public static string BankAccountName {
            get {
                return ResourceManager.GetString("BankAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Number.
        /// </summary>
        public static string BankNumber {
            get {
                return ResourceManager.GetString("BankNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelProcess {
            get {
                return ResourceManager.GetString("CancelProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send password because system does not find any email associated with this account. Please contact the support department for assistance..
        /// </summary>
        public static string cantSendpass {
            get {
                return ResourceManager.GetString("cantSendpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string changedpass {
            get {
                return ResourceManager.GetString("changedpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password customer :.
        /// </summary>
        public static string ChangePassCus {
            get {
                return ResourceManager.GetString("ChangePassCus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password In The First Time.
        /// </summary>
        public static string ChangePassFirst {
            get {
                return ResourceManager.GetString("ChangePassFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (In the first login time, you should change default password by system to ensure  security safe !!! ).
        /// </summary>
        public static string ChangePassText {
            get {
                return ResourceManager.GetString("ChangePassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Detail Invoice..
        /// </summary>
        public static string ChiTietHoaDon {
            get {
                return ResourceManager.GetString("ChiTietHoaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not published.
        /// </summary>
        public static string ChuaPhatHanh {
            get {
                return ResourceManager.GetString("ChuaPhatHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not paymented.
        /// </summary>
        public static string ChuaThanhToan {
            get {
                return ResourceManager.GetString("ChuaThanhToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not viewed.
        /// </summary>
        public static string ChuaXem {
            get {
                return ResourceManager.GetString("ChuaXem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string createdpass {
            get {
                return ResourceManager.GetString("createdpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurPass {
            get {
                return ResourceManager.GetString("CurPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CusCode {
            get {
                return ResourceManager.GetString("CusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CusName {
            get {
                return ResourceManager.GetString("CusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cusomer Type.
        /// </summary>
        public static string CusType {
            get {
                return ResourceManager.GetString("CusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login .
        /// </summary>
        public static string DangNhap {
            get {
                return ResourceManager.GetString("DangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string DaPhatHanh {
            get {
                return ResourceManager.GetString("DaPhatHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paymented.
        /// </summary>
        public static string DaThanhToan {
            get {
                return ResourceManager.GetString("DaThanhToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewed.
        /// </summary>
        public static string DaXem {
            get {
                return ResourceManager.GetString("DaXem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed by VNPT Software.
        /// </summary>
        public static string designedby {
            get {
                return ResourceManager.GetString("designedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely yours!.
        /// </summary>
        public static string EmailFooter {
            get {
                return ResourceManager.GetString("EmailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear,.
        /// </summary>
        public static string EmailTitle {
            get {
                return ResourceManager.GetString("EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        public static string EnterAddr {
            get {
                return ResourceManager.GetString("EnterAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Customer name.
        /// </summary>
        public static string EnterCusName {
            get {
                return ResourceManager.GetString("EnterCusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string enternewpass {
            get {
                return ResourceManager.GetString("enternewpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enter password.
        /// </summary>
        public static string EnterPass {
            get {
                return ResourceManager.GetString("EnterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter invoice code.
        /// </summary>
        public static string enterSearchinvoice {
            get {
                return ResourceManager.GetString("enterSearchinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enter username (cuscode).
        /// </summary>
        public static string EnterUser {
            get {
                return ResourceManager.GetString("EnterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string equalpass {
            get {
                return ResourceManager.GetString("equalpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password you enter not match. Please try again..
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not yet invoice..
        /// </summary>
        public static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmEmail failed.
        /// </summary>
        public static string errorConfirmEmail {
            get {
                return ResourceManager.GetString("errorConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect formats email.
        /// </summary>
        public static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string erroroccurred {
            get {
                return ResourceManager.GetString("erroroccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password you enter not match. Please try again..
        /// </summary>
        public static string ErrorPass {
            get {
                return ResourceManager.GetString("ErrorPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax: (0511) 3 847 666.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice paymented.
        /// </summary>
        public static string HasBill {
            get {
                return ResourceManager.GetString("HasBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string InforCus {
            get {
                return ResourceManager.GetString("InforCus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in total.
        /// </summary>
        public static string InTotal {
            get {
                return ResourceManager.GetString("InTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce.
        /// </summary>
        public static string Introduce {
            get {
                return ResourceManager.GetString("Introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down with *.inv.
        /// </summary>
        public static string InvDown {
            get {
                return ResourceManager.GetString("InvDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Adjust Descrease.
        /// </summary>
        public static string InvoiceAdjustD {
            get {
                return ResourceManager.GetString("InvoiceAdjustD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Adjust Increase.
        /// </summary>
        public static string InvoiceAdjustIn {
            get {
                return ResourceManager.GetString("InvoiceAdjustIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Adjust Information.
        /// </summary>
        public static string InvoiceAdjustInfor {
            get {
                return ResourceManager.GetString("InvoiceAdjustInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Invoice.
        /// </summary>
        public static string InvoiceNormal {
            get {
                return ResourceManager.GetString("InvoiceNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Not Found.
        /// </summary>
        public static string InvoiceNotFound {
            get {
                return ResourceManager.GetString("InvoiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Replaced.
        /// </summary>
        public static string InvoiceReplace {
            get {
                return ResourceManager.GetString("InvoiceReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Invoice Portal.
        /// </summary>
        public static string InvoiceReseach {
            get {
                return ResourceManager.GetString("InvoiceReseach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        public static string KyHieu {
            get {
                return ResourceManager.GetString("KyHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string leastlong {
            get {
                return ResourceManager.GetString("leastlong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices list of .
        /// </summary>
        public static string ListBill {
            get {
                return ResourceManager.GetString("ListBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Customer.
        /// </summary>
        public static string ListCustomer {
            get {
                return ResourceManager.GetString("ListCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listed.
        /// </summary>
        public static string Listed {
            get {
                return ResourceManager.GetString("Listed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices List By PDF.
        /// </summary>
        public static string ListInvByPDF {
            get {
                return ResourceManager.GetString("ListInvByPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginSystem {
            get {
                return ResourceManager.GetString("LoginSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name can&apos;t too long 150 character..
        /// </summary>
        public static string LongestName {
            get {
                return ResourceManager.GetString("LongestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t too long 150 character..
        /// </summary>
        public static string LongestUsername {
            get {
                return ResourceManager.GetString("LongestUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Matkhau {
            get {
                return ResourceManager.GetString("Matkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string MauSo {
            get {
                return ResourceManager.GetString("MauSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        public static string MST {
            get {
                return ResourceManager.GetString("MST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAGUNA Company(VIETNAM).
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        public static string NgayXuat {
            get {
                return ResourceManager.GetString("NgayXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice no payment.
        /// </summary>
        public static string NotBill {
            get {
                return ResourceManager.GetString("NotBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification from system.
        /// </summary>
        public static string NoteFromSystem {
            get {
                return ResourceManager.GetString("NoteFromSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not exist your account in system. Please contact Support team to get more information..
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invoice hasnt been settled. please pay it!.
        /// </summary>
        public static string notpayinvoice {
            get {
                return ResourceManager.GetString("notpayinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send password because your account not exist email address in system. Please contact support team to get more information..
        /// </summary>
        public static string NotSend {
            get {
                return ResourceManager.GetString("NotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter invoice code.
        /// </summary>
        public static string nullinvhash {
            get {
                return ResourceManager.GetString("nullinvhash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages:  Home | Facebook | Tripadvisor.
        /// </summary>
        public static string PageHome {
            get {
                return ResourceManager.GetString("PageHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous page.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Password.
        /// </summary>
        public static string RecentPass {
            get {
                return ResourceManager.GetString("RecentPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember ?.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember ?.
        /// </summary>
        public static string Remember1 {
            get {
                return ResourceManager.GetString("Remember1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reenter New Password.
        /// </summary>
        public static string ReNewPass {
            get {
                return ResourceManager.GetString("ReNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represent Person.
        /// </summary>
        public static string RepresentPerson {
            get {
                return ResourceManager.GetString("RepresentPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password by enter your code?.
        /// </summary>
        public static string ResetPassText {
            get {
                return ResourceManager.GetString("ResetPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Changed.
        /// </summary>
        public static string SaveChanged {
            get {
                return ResourceManager.GetString("SaveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH INVOICE.
        /// </summary>
        public static string searchinvoice {
            get {
                return ResourceManager.GetString("searchinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password successfully! Please access email address .
        /// </summary>
        public static string SendOK1 {
            get {
                return ResourceManager.GetString("SendOK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to check account information..
        /// </summary>
        public static string SendOK2 {
            get {
                return ResourceManager.GetString("SendOK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        public static string SoHoaDon {
            get {
                return ResourceManager.GetString("SoHoaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string Stt {
            get {
                return ResourceManager.GetString("Stt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string taikhoan {
            get {
                return ResourceManager.GetString("taikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cus Tax Code.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.: (0511) 3 847 333.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string TenDangNhap {
            get {
                return ResourceManager.GetString("TenDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Name.
        /// </summary>
        public static string TenHoaDon {
            get {
                return ResourceManager.GetString("TenHoaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Status.
        /// </summary>
        public static string ThanhToan {
            get {
                return ResourceManager.GetString("ThanhToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Balance.
        /// </summary>
        public static string TongTien {
            get {
                return ResourceManager.GetString("TongTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to view invoice..
        /// </summary>
        public static string Toviewinv {
            get {
                return ResourceManager.GetString("Toviewinv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Status.
        /// </summary>
        public static string TrangThai {
            get {
                return ResourceManager.GetString("TrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username (customer code) is incorrect..
        /// </summary>
        public static string usernotExist {
            get {
                return ResourceManager.GetString("usernotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found..
        /// </summary>
        public static string userNotFound {
            get {
                return ResourceManager.GetString("userNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Invoice.
        /// </summary>
        public static string VATInvoice {
            get {
                return ResourceManager.GetString("VATInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string ViewFromDate {
            get {
                return ResourceManager.GetString("ViewFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website: &lt;a href=&quot;www.furamavietnam.com&quot;&gt;www.furamavietnam.com&lt;/a&gt;.
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Status.
        /// </summary>
        public static string XemHoaDon {
            get {
                return ResourceManager.GetString("XemHoaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View PDF..
        /// </summary>
        public static string XemPDF {
            get {
                return ResourceManager.GetString("XemPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must.
        /// </summary>
        public static string Youmust {
            get {
                return ResourceManager.GetString("Youmust", resourceCulture);
            }
        }
    }
}
